name: Build Windows EXE (Static)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-libjpeg-turbo
          mingw-w64-x86_64-ca-certificates

    - name: Build Static EXE
      shell: msys2 {0}
      run: |
        gcc main.c -o mapbot.exe \
          -static -static-libgcc -static-libstdc++ \
          -ljpeg -lcurl \
          -lws2_32 -lwldap32 -lcrypt32 -lbcrypt \
          -lm

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: mapbot
        path: mapbot.exe
